apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: sensors_live_index
    jsonData:
      flavor: elasticsearch
      version: "7.17.0"
      timeField: ingest_ts
      maxConcurrentShardRequests: 5
      logMessageField: ""
      logLevelField: ""
    isDefault: true
    editable: true

  - name: Elasticsearch-NodeStatus
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: node_status_index
    jsonData:
      flavor: elasticsearch
      version: "7.17.0"
      timeField: last_update_ts
      maxConcurrentShardRequests: 5
    isDefault: false
    editable: true
